## Matrix multiplication in NumPy

First of all note that the __matrix multiplication__ operation can be implemented in NumPy using the dot() function.

The usual rule applies: Given two matrices A, B, if  matrix A has the dimensions m rows and n columns and matrix B has the dimensions n and k. Then the n columns in A and n rows of B must be equal. The computation C=A*B is a new matrix C with m rows and k columns.


In [24]:
from numpy import array, shape, random, ones, linalg
A = array([[1, 2], [3, 4], [5, 6]])
print('shape A:',shape(A))
print(A)
B = array([[1, 2], [3, 4]])
print('shape B:',shape(B))
print(B)
C = A.dot(B)  # Matrix  multiplication C=A*B
print('shape C:',shape(C))
print(C)

shape A: (3, 2)
[[1 2]
 [3 4]
 [5 6]]
shape B: (2, 2)
[[1 2]
 [3 4]]
shape C: (3, 2)
[[ 7 10]
 [15 22]
 [23 34]]


## Matrix-vector multiplication in NumPy

The __matrix-vector multiplication__ operation can be performed in NumPy using the dot() function as long as the rule of matrix multiplication is observed.

Specifically, that the number of columns in the matrix must equal the number of items in the vector. As with matrix multiplication, the operation can be written using the dot notation. __Because the vector only has one column, the result is always a vector.__

In [25]:
A = array([[1, 2], [3, 4], [5, 6]])
print('shape A:',shape(A))
print(A)
B = array([0.5, 0.5])
print('shape B:',shape(B))
print(B)
C = A.dot(B)
print('shape C:',shape(C))
print(C)

shape A: (3, 2)
[[1 2]
 [3 4]
 [5 6]]
shape B: (2,)
[0.5 0.5]
shape C: (3,)
[1.5 3.5 5.5]


#### Consider the following operation

$\vec h = {\bf X} \left( {\bf X}^T {\bf X} \right)^{-1} \vec c$

where ${\bf X}$ is an $m \times n$ matrix and $c$ is a $n \times 1$ row vector. Then

$ {\bf A } = {\bf X}^T {\bf X}$ is a matrix multiplication where A is an $n \times n$ matrix

${\bf B } = {\bf X} \left( {\bf A} \right)^{-1}$ is a matrix multiplication where B is a $m \times n$ matrix

${\bf C } = {\bf B} \vec c$ is a matrix-vector multiplication where C is an $m \times 1$ vector



In [26]:
# So if,
random.seed( 235 )
X = random.ranf((10,3))
c = ones(3)
print(shape(X))
print(shape(c))

(10, 3)
(3,)


You can check that A, B, C have the shapes above.