# HOMEWORK 9 (40 pts)

In [6]:
# Numpy setup
import numpy as np
np.set_printoptions(precision=3)

### Post-video questions (1 pt each)

In [7]:
# Given
np.random.seed( 23 )
mat = np.random.ranf((5,6))

In [8]:
print(np.shape(mat))  # Check the shape
print(mat) # print the matrix (for reference)

(5, 6)
[[5.173e-01 9.470e-01 7.655e-01 2.824e-01 2.210e-01 6.862e-01]
 [1.671e-01 3.924e-01 6.181e-01 4.119e-01 2.465e-03 8.840e-01]
 [8.849e-01 3.004e-01 5.896e-01 9.784e-01 8.451e-01 6.508e-02]
 [2.947e-01 2.879e-01 8.225e-01 6.262e-01 1.105e-01 5.288e-04]
 [9.422e-01 1.415e-01 4.216e-01 3.465e-01 8.698e-01 4.286e-01]]


#### Q1 Print the second column of data to the console.

In [9]:
print(mat[:,1]) # ":" means all indices along 0 axis (i.e. rows) , 1 is second column

[0.947 0.392 0.3   0.288 0.142]


#### Q2 Print the lower right 2×2 portion of the matrix.

In [10]:
print(mat[3:5,4:6])

[[1.105e-01 5.288e-04]
 [8.698e-01 4.286e-01]]


#### Q3 Print the average of the entire matrix and the average of the columns. (Do not use _for_ or _while_ loops.)

In [19]:
print(np.mean(mat))
print('Average of all columns:')
print(np.mean(mat, axis=0))

0.49504848821354275
Average of all columns:
[0.561 0.414 0.643 0.529 0.41  0.413]


In [12]:
# You can also do individual columns:
print('{:.3f}'.format(mat[:,0].mean())) # first column
print('{:.3f}'.format(mat[:,1].mean())) # second column
# etc...

0.561
0.414


Do the following using __numpy__. Do not use _for_ or _while_ loops. Each of these steps should be one short Python line + one line to print. 

Hint: Explore the NumPy documentation to consider use of the function: “np.arange”.

* Q4: Create a matrix of zeros that has 2 columns and 6 rows.
* Q5: Fill the first column with (0,1,2,3,4,5)
* Q6: The first column is associated with the value of $x$. Fill the second column with $y=x^2-x$


In [13]:
# Q4
a = np.zeros((6,2))
print(a) 

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [14]:
# Q5
a[:,0] = np.arange(0.,6.)
print(a)

[[0. 0.]
 [1. 0.]
 [2. 0.]
 [3. 0.]
 [4. 0.]
 [5. 0.]]


In [15]:
# Q6
a[:,1] = a[:,0]**2 - a[:,0]
print(a)

[[ 0.  0.]
 [ 1.  0.]
 [ 2.  2.]
 [ 3.  6.]
 [ 4. 12.]
 [ 5. 20.]]


#### Q7 Use a single command to find _all_ of the elements that are greater than 0.7

In [16]:
print(a > 0.7)

[[False False]
 [ True False]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]]


#### Q8 Use the results from the previous problem, and in a single command print out the _values_ of the elements in the matrix that are above 0.7.

In [18]:
print(a)
print(a[a > 0.7])

[[ 0.  0.]
 [ 1.  0.]
 [ 2.  2.]
 [ 3.  6.]
 [ 4. 12.]
 [ 5. 20.]]
[ 1.  2.  2.  3.  6.  4. 12.  5. 20.]


## Problem 1 (3 pts)
Create a vector of 10,000,000 random elements using a function from __numpy.random__. 

Compute the average of this vector using the __old-fashioned, slow, for loop method__. Show the code and the result.

In [6]:
vec = np.random.rand(10000000)
sm = 0
for i in vec:
    sm += i
print (sm/len(vec))

0.5000554394406679


## Problem 2 (1 pts)

Compute the average using a __numpy__ function. Show the code and the result.

In [15]:
print(vec.mean())

0.5000554394405515


## Problem 3 (6 pts)

The __time.time()__ function will return the current time in terms of seconds. It is possible to determine the __computational time__ of a process by capturing the time before and after the execution of the process. Write a Python script to compute the __computational time__ for the previous two problems. Do not get a new vector, and do not include the creation of the random vector in your timing.

Compute the __ratio__ of the time to compute the average using Problem 1 to the time it took to compute the answer using the method in Problem 2. Show your codes, the times for each method, and the ratio.

In [9]:
import time
t1 = time.time()
sm = 0
for i in vec:
    sm += i
t2 = time.time()
vec.mean()
t3= time.time()
print('slow: {:.5f} fast: {:.5f} ratio: {:.5f} or {:.5f} '.format(t2-t1, t3-t2, (t2-t1)/(t3-t2), (t3-t2)/(t2-t1)))
# Note that the numbers below may differ from your results

slow: 1.66069 fast: 0.00723 ratio: 229.75407 or 0.00435 


## Problem 4 (3 pts)

Use the numpy random seed value of 23423. Create three random vectors, each of length 5. These are named $a$,$b$,and $c$. 

Compute $d=a+b×c$. Show your code and all four vectors.


In [10]:
np.random.seed( 23423 )
a = np.random.rand(5)
b = np.random.rand(5)
c = np.random.rand(5)
d = a + b*c
print('a:',a)
print('b:',b)
print('c:',c)
print('d:',d)

a: [0.891 0.045 0.59  0.743 0.545]
b: [0.006 0.466 0.566 0.06  0.322]
c: [0.046 0.307 0.939 0.888 0.544]
d: [0.891 0.189 1.122 0.797 0.721]


## Problem 5 (3 pts)

Create a $5 × 5$ matrix of random values. Use the seed of 453. Using the random slicing technique, write a Python command that retrieves values for the following locations in the matrix $(1,3)$, $(2,2)$, $(3,1)$.

In [57]:
x = [1,2,3]
y = [3,2,1]
np.random.seed( 453 )
mat = np.random.ranf((5,5))
print(mat[x,y])

[0.171 0.199 0.303]


## Problem 6 (4 pts)

Recall the equation used for an object falling under the influence of gravity,

$$y_2 = y_1 + v_1 t + \frac{1}{2} g t^2 $$

Start with a height of $600$ m.  Your task is to compute the height of the object for ten different experiments.  The experiments differ in the amount of time the object drops: $t = ( 1, 2, 3, 4, 5, 6, 7, 8, 9, 10)$ all in seconds.  To compute the $y_2$ values for all experiments, use,

$$\vec y_2 = \vec y_1 +  \frac{1}{2} g {\vec t}^2 $$

Once the data variables are assigned, this computation can be done in one line of Python.  Show your code and the results.


In [58]:
dt = np.array((1,2,3,4,5,6,7,8,9,10))
y0 = 600
g = -9.8
y2 = y0 + 0.5*g*dt*dt
print(y2)

[595.1 580.4 555.9 521.6 477.5 423.6 359.9 286.4 203.1 110. ]


## Problem 7 (6 pts)

Recall the chaos equation: 

$$x_{n+1} = r x_n (1-x_n).$$


Python does not offer tools to solve this equation efficiently because it is a recursive equation.  The answer to $x_n$ is needed before $x_{n+1}$ can be computed.  However, it is possible to use NumPy tools to efficiently calculate the results for several trials using different values of $r$.

Create a vector $rvec$ which has the values $(2, 2.3, 2.8, 3, 3.3,, 4.0)$.  Create a matrix $mat$ which is $50 \times 6$.  In a single command set the values of the top row of the matrix to 0.1. (This was the initial starting value of $x$.)  Each row in this matrix will be one iteration of the equation and each column is one trial.  Create a __for__ loop that spans the number of iterations (49).  Inside the __for__ loop there should be a single line that calculates the values for all trials in a single row. 

The first values in the first column correspond to the experiment when $r = 2.0$.  The $x$ value in this trial stabilizes at 0.5.  Thus, the last four values in the first column should be 0.5.  In a single Python command, print out the last for rows for all columns.  These values should match the results from the lecture.


In [20]:
mat = np.zeros((50,6))
mat[0] = 0.1

# Create "r" vector
rvec= np.array((2,2.5,2.8,3,3.3,4))

for i in range( 1,50):
    mat[i] = rvec*mat[i-1]*(1-mat[i-1])
    
# print out the last four rows for all columns
print(mat[-4:])

[[0.5   0.6   0.643 0.634 0.479 0.997]
 [0.5   0.6   0.643 0.696 0.824 0.011]
 [0.5   0.6   0.643 0.635 0.479 0.044]
 [0.5   0.6   0.643 0.695 0.824 0.168]]


## Problem 8 (6 pts)

Consider the case in which the goal is to find a vector $\vec h$ such that,
$$\vec h \cdot \vec x_i = 1.$$
The $\vec x_i$ represents a vector from a set of vectors.  The equations states that the dot product of the vector $\vec h$ with _any_ of the $\vec x$ vectors is 1.0.  The task of this assignment is to find $\vec h$ for a given set of $\vec x$ vectors.

The solution starts with creating a matrix __X__ in which each of the columns is one of the $\vec x$ vectors.  The code for generating this matrix is:
```cython
np.random.seed( 235 )
X = np.random.ranf((10,3))
```

It can be shown that the equation to find $\vec h$ is

$$\vec h = {\bf X} \left( {\bf X}^T {\bf X} \right)^{-1} \vec c$$

or alternatively,

$$\vec h = \left( {\bf X}^T {\bf X} \right)^{-1} {\bf X^T}  \vec c$$


The $X^T$ is the transpose, and the superscript -1 is the inverse and the vector $\vec c = (1,1,1)$.  The length of $\vec c$ is the same as the number of vectors used to make ${\bf X}$.

Write a Python script to compute $\vec h$.  Show your codes and results.  Confirm your results by computing $\vec h \cdot \vec x_i$ where $x_i$ is a column from ${\bf X}$.  There are three columns in ${\bf X}$, so you should confirm the $\vec h$ for each column.


In [33]:
# Given:
np.random.seed( 235 )
X = np.random.ranf((10,3))

# Build expression:
Q = X.T.dot(X)
c = np.ones(3)
Qi = np.linalg.inv(Q)
a = Qi.dot(c)
h = X.dot(a)
# or 
# h = a.dot(X.T)

# Print results
print('Shape h: ',np.shape(h))
print('h: ', h)
print("Verify that 'h.x = 1' :")
# Note that formatting "removes" the round-off error
print('{:.3f}'.format(h.dot(X[:,0])))
print('{:.3f}'.format(h.dot(X[:,1])))
print('{:.3f}'.format(h.dot(X[:,2])))

Shape h:  (10,)
h:  [ 0.158  0.237 -0.068 -0.037  0.362  0.125  0.281  0.428  0.204  0.391]
Verify that 'h.x = 1' :
1.000
1.000
1.000
